import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import Link from "next/link";

export const metadata = {
  title: "Terms & Conditions",
  description:
    "Terms and conditions for using the Remawt AI video creation platform. Covers accounts, credits, payments, acceptable use, and intellectual property.",
  alternates: { canonical: "/terms" },
};

const SECTIONS: { h: string; body: React.ReactNode }[] = [
  {
    h: "1. Acceptance of Terms",
    body: (
      <p>
        By accessing or using Remawt (&quot;the Service&quot;), operated by
        Remawt (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;), you agree
        to be bound by these Terms & Conditions. If you do not agree, do not use
        the Service.
      </p>
    ),
  },
  {
    h: "2. Description of Service",
    body: (
      <p>
        Remawt is an AI-powered video generation platform that allows users to
        create professional motion graphics, product demos, and explainer
        videos. The Service includes website scraping, AI content analysis, code
        generation, and video rendering capabilities.
      </p>
    ),
  },
  {
    h: "3. Account Registration",
    body: (
      <ul className="list-disc space-y-1.5 pl-6">
        <li>You must provide accurate and complete information.</li>
        <li>You are responsible for maintaining account security.</li>
        <li>You must be at least 16 years of age.</li>
        <li>One person or entity may not maintain more than one account.</li>
        <li>You are responsible for all activity under your account.</li>
      </ul>
    ),
  },
  {
    h: "4. Credits and Payments",
    body: (
      <ul className="list-disc space-y-1.5 pl-6">
        <li>Credits are required to generate and export videos.</li>
        <li>Each video export costs 1 credit regardless of length or quality.</li>
        <li>Credits are non-refundable once purchased.</li>
        <li>Credits do not expire.</li>
        <li>Prices are subject to change with reasonable notice.</li>
        <li>Payments are processed securely through Dodo Payments.</li>
        <li>Annual plans are billed as a single upfront payment for 12 months.</li>
      </ul>
    ),
  },
  {
    h: "5. Acceptable Use",
    body: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul className="mt-2 list-disc space-y-1.5 pl-6">
          <li>Generate illegal, harmful, threatening, or defamatory content.</li>
          <li>Create misleading or deceptive content (deepfakes, impersonation).</li>
          <li>Infringe on intellectual property rights.</li>
          <li>Distribute malware or conduct phishing.</li>
          <li>Attempt unauthorized access to the Service or its systems.</li>
          <li>Scrape data from the Service beyond normal use.</li>
          <li>Resell or redistribute the Service without authorization.</li>
          <li>Generate content depicting minors in harmful situations.</li>
        </ul>
      </>
    ),
  },
  {
    h: "6. Intellectual Property",
    body: (
      <>
        <p className="mono-tick">YOUR CONTENT</p>
        <p className="mt-2">
          You retain ownership of the content you create using the Service. By
          using the Service, you grant us a limited license to process your
          inputs (URLs, text, preferences) solely to generate your requested
          content.
        </p>
        <p className="mono-tick mt-6">OUR PLATFORM</p>
        <p className="mt-2">
          The Service — its code, design, features, and branding — is owned by
          Remawt and protected by intellectual property laws. You may not copy,
          modify, or reverse-engineer any part of the Service.
        </p>
      </>
    ),
  },
  {
    h: "7. AI-Generated Content",
    body: (
      <ul className="list-disc space-y-1.5 pl-6">
        <li>Content is generated by AI models and may not always be accurate.</li>
        <li>You are responsible for reviewing all generated content before use.</li>
        <li>We do not guarantee content will be free from errors or biases.</li>
        <li>Generated videos must comply with the laws of your jurisdiction.</li>
      </ul>
    ),
  },
  {
    h: "8. Service Availability",
    body: (
      <p>
        We strive to provide reliable service but do not guarantee uninterrupted
        access. The Service may be temporarily unavailable due to maintenance,
        updates, or circumstances beyond our control.
      </p>
    ),
  },
  {
    h: "9. Limitation of Liability",
    body: (
      <>
        <p>
          To the maximum extent permitted by law, Remawt shall not be liable for
          any indirect, incidental, special, consequential, or punitive damages.
        </p>
        <p className="mt-3">
          Our total liability shall not exceed the amount you paid to us in the
          12 months preceding the claim.
        </p>
      </>
    ),
  },
  {
    h: "10. Termination",
    body: (
      <p>
        We reserve the right to suspend or terminate your account at any time
        for violation of these terms. Unused credits are non-refundable upon
        termination for cause.
      </p>
    ),
  },
  {
    h: "11. Indemnification",
    body: (
      <p>
        You agree to indemnify and hold harmless Remawt from any claims arising
        from your use of the Service or violation of these terms.
      </p>
    ),
  },
  {
    h: "12. Changes to Terms",
    body: (
      <p>
        We may modify these terms at any time. Material changes will be
        communicated via email or through the Service. Continued use after
        changes constitutes acceptance.
      </p>
    ),
  },
  {
    h: "13. Governing Law",
    body: (
      <p>
        These terms shall be governed by applicable laws. Disputes shall be
        resolved through good-faith negotiation, and if necessary, binding
        arbitration.
      </p>
    ),
  },
  {
    h: "14. Contact",
    body: (
      <p>
        For questions, contact{" "}
        <a
          href="mailto:support@remawt.com"
          className="text-ink underline decoration-rule-strong underline-offset-4 hover:decoration-ink"
        >
          support@remawt.com
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface text-ink">
      <Navbar />

      <section className="border-b border-rule px-6 pb-12 pt-32">
        <div className="mx-auto max-w-[1400px]">
          <div className="mb-10 flex flex-wrap items-center gap-3 border-b border-rule pb-4">
            <span className="mono-label rounded-sm border border-ink px-2 py-1">
              LEGAL · TERMS · v1
            </span>
            <span className="mono-tick">LAST UPDATED 2026-03-11</span>
          </div>
          <h1 className="text-[clamp(2.5rem,7vw,6rem)] font-medium leading-[0.95] tracking-[-0.02em]">
            Terms & <span className="font-serif-italic">conditions.</span>
          </h1>
        </div>
      </section>

      <section className="px-6 py-20">
        <div className="mx-auto grid max-w-[1400px] grid-cols-1 gap-12 lg:grid-cols-12">
          {/* TOC */}
          <aside className="lg:col-span-3">
            <p className="mono-tick mb-4">CONTENTS</p>
            <ul className="space-y-2 text-sm">
              {SECTIONS.map((s) => (
                <li key={s.h}>
                  <a
                    href={`#${s.h.split(".")[0]}`}
                    className="text-muted hover:text-ink"
                  >
                    {s.h}
                  </a>
                </li>
              ))}
            </ul>
          </aside>

          {/* Body */}
          <div className="lg:col-span-9">
            <div className="space-y-12 text-base leading-relaxed text-ink/85">
              {SECTIONS.map((s) => (
                <div key={s.h} id={s.h.split(".")[0]}>
                  <h2 className="font-serif-italic text-2xl text-ink">{s.h}</h2>
                  <div className="mt-3">{s.body}</div>
                </div>
              ))}
            </div>

            <div className="mt-16 flex gap-6 border-t border-rule pt-6 text-sm">
              <Link
                href="/privacy"
                className="text-muted hover:text-ink"
              >
                Privacy Policy
              </Link>
              <Link
                href="/pricing"
                className="text-muted hover:text-ink"
              >
                Pricing
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
